services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: football-predictor-api
    restart: unless-stopped
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: football-predictor-streamlit
    restart: unless-stopped
    environment:
      API_URL: "http://api:8000"
    ports:
      - "8501:8501"
    depends_on:
      - api